services:
  db:
    image: postgres:15
    container_name: postgres-goauth
    environment:
      POSTGRES_USER: goauth_user
      POSTGRES_PASSWORD: think
      POSTGRES_DB: goauth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: